### ISSUE TITLE
Where is the base directory ?

### ISSUE THREAD

**Issue by aloulouamine** [voidberg/jasmine-bamboo-reporter#2]
I don't find report.json in the end of my tests.

**Comment by voidberg** [comment]
The file should be `jasmine.json` or `jasmine-results.json` if you followed the tutorial. It's supposed to be in the root of your project, by default.

**Comment by arjan674** [comment]
Hi,
I followed the documentation and after running the test I couldn't find the "jasmine-results.json" either.
I have searched through the whole project.
